version: '3.5'


services:
  postgres:
    container_name: postgres
    build: "."
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       - "./init.sh:/scripts/init.sh"
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local
    
